name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "Atul Kumar Jena"
        git config --global user.email "jenaatul8@gmail.com"

    - name: Add and Commit changes
      run: |
        git add CNAME
        git commit -m "Setup gh-pages branch"

    - name: Push changes
      run: |
        git push origin gh-pages
